# Generated by Django 4.1.3 on 2022-12-14 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('random_sequence', models.CharField(default='john', max_length=10)),
                ('bio', models.TextField()),
                ('pic_first', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('human', 'Human'), ('identicon', 'Identicon'), ('initials', 'Initials'), ('bottts', 'Bottts'), ('avataaars', 'Avataaars'), ('jdenticon', 'Jdenticon'), ('gridy', 'Gridy'), ('micah', 'Micah')], default='male', max_length=20)),
                ('department', models.CharField(choices=[('TECH', 'tech'), ('ACOUNING', 'acounting'), ('ENVIRO', 'enviro'), ('WAREHOUSE', 'warehouse'), ('QUALITY', 'quality')], default='TECH', max_length=30)),
            ],
        ),
    ]
