# Generated by Django 4.1.3 on 2022-12-07 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('person_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pic', models.URLField(default='https://avatars.dicebear.com/api/initials/<django.db.models.fields.related.OneToOneField>.svg')),
                ('bio', models.TextField()),
                ('department', models.IntegerField(choices=[(1, 'tech'), (2, 'acounting'), (3, 'enviro'), (4, 'warehouse'), (5, 'quality')], default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
