# Generated by Django 4.1.3 on 2022-12-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_auth', '0004_profile_random_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic_first',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('human', 'Male'), ('identicon', 'Male'), ('initials', 'Male'), ('bottts', 'Male'), ('avataaars', 'Male'), ('jdenticon', 'Male'), ('gridy', 'Male'), ('micah', 'Male')], default='male', max_length=20),
        ),
    ]
