# Generated by Django 4.1.3 on 2022-12-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_auth', '0005_alter_profile_pic_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('TECH', 'tech'), ('ACOUNING', 'acounting'), ('ENVIRO', 'enviro'), ('WAREHOUSE', 'warehouse'), ('QUALITY', 'quality')], default='TECH', max_length=30),
        ),
    ]
