# Generated by Django 4.1.3 on 2022-12-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_auth', '0006_alter_profile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic_first',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('human', 'Human'), ('identicon', 'Identicon'), ('initials', 'Initials'), ('bottts', 'Bottts'), ('avataaars', 'Avataaars'), ('jdenticon', 'Jdenticon'), ('gridy', 'Gridy'), ('micah', 'Micah')], default='male', max_length=20),
        ),
    ]
