# Generated by Django 4.1.3 on 2022-11-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
