# Generated by Django 4.1.3 on 2022-12-20 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hour', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SickHour',
        ),
    ]
