# Generated by Django 4.1.3 on 2022-11-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hour', '0002_alter_day_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='extra',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='lunch_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='lunch_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='required',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
