# Generated by Django 4.1.3 on 2022-12-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hour', '0004_alter_day_options_alter_day_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
