# Generated by Django 4.1.3 on 2022-12-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hour', '0007_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='public_holiday',
            field=models.BooleanField(default=False),
        ),
    ]
